### ISSUE TITLE
An error about alipay plugin,plugin_not_installed

### ISSUE THREAD

**Issue by 442623641** [pipitang/cordova-alipay-base#11]
**WARN: Native: tried calling Alipay.pay, but the Alipay plugin is not installed.**
I did everything I could ,like `cordova plugin add cordova-alipay-base --variable ALI_PID=xxxxx`,`npm install --save @ionic-native/alipay`，even remove the platform `cordova rm platform ios` and add the platform again `cordova add platform ios`. I checked the source code, but nothing was found, forgive me for not being professional.I guess it's the path that leads to bug about packages.pls note my env info：
 **global packages:**

    cordova (Cordova CLI) : 7.1.0 

**local packages:**

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3 ios 4.5.3
    Ionic Framework    : ionic-angular 3.8.0

**System**:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v7.9.0
    npm        : 4.2.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55

**Comment by open-more** [comment]
same error happened.

**Comment by azri-hamza** [comment]
I have the same problem. Any help please.
