### ISSUE TITLE
android 7.0环境下无法打包,并且会扰乱其他插件安装

### ISSUE THREAD

**Issue by MyCupOfTeaOo** [pipitang/cordova-alipay-base#14]
android 7.0环境下无法打包,并且会扰乱其他插件安装
![image](https://user-images.githubusercontent.com/29906873/38131078-2bd31374-3438-11e8-8b6b-60668f09dbd9.png)

**Comment by nsioo** [comment]
同、资源包放到libs目录， cordova android@7.1会判断成Eclipse项目，干扰其他插件安装
