### ISSUE TITLE
Error: Variable(s) missing (use: --variable ALI_PID=value).

### ISSUE THREAD

**Issue by match08** [pipitang/cordova-alipay-base#2]
Error: Variable(s) missing (use: --variable ALI_PID=value).

**Comment by match08** [comment]
加id后就会报错

**Comment by crossmo** [comment]
iOS or Android, 嘛错误？

**Comment by match08** [comment]
cordova plugin add 的时候后面把pid加上不行 报这个错误

**Comment by crossmo** [comment]
哥们，笔误，不应该用 ```--variables``` 而是 ```--variable```

**Comment by match08** [comment]
好的 谢谢 没注意

**Comment by crossmo** [comment]
是我写错，哈。
