### ISSUE TITLE
在ios上怎么报错 启动不来，android可以

### ISSUE THREAD

**Issue by match08** [pipitang/cordova-alipay-base#4]
在ios上怎么报错 启动不来，android可以

**Comment by pipitang** [comment]
这个。。。具体点？我们项目在用，没问题哦。。。

cordova卸载再安装有问题，卸不干净，装得也就不干净。如果你装过老版本的话，建议你手工删，或者直接干掉ios platform，再重新装。

**Comment by match08** [comment]
错误如下：
 -[__NSCFString allKeys]: unrecognized selector sent to instance 0x13e13a220
**\* WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[__NSCFString allKeys]: unrecognized selector sent to instance 0x13e13a220

**Comment by pipitang** [comment]
这个看起来不像这个插件的问题，你启动之后控制台看见：

```
Loaded alipay plugin with xxx
```

就表明支付控件已经起来了。

插件启动唯一干的事情就是读取ali_pid

```

-(void)pluginInitialize
{
    self.aliPID = [[self.commandDelegate settings] objectForKey:@"ali_pid"];
    NSLog(@"Loaded alipay plugin with %@", self.aliPID);
}

```

**Comment by match08** [comment]
allkeys 这个数组获取报错了，在这里停住了

**Comment by match08** [comment]
发现ios串的是json是吗？，不是&字符串？

**Comment by andyhuang15** [comment]
我这边好像也是报这个错误，请问一下怎么解决的
-[__NSCFString allKeys]: unrecognized selector sent to instance 0x1006ef430
[1384:771702] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[__NSCFString allKeys]: unrecognized selector sent to instance 0x1006ef430
