### ISSUE TITLE
ios 抛出一个bug ，ios版本9.1

### ISSUE THREAD

**Issue by match08** [pipitang/cordova-alipay-base#5]
allkeys 这个数组获取有问题，在这里停住了

**Comment by pipitang** [comment]
我们真机和模拟器都测试过，没问题的，你cordova什么版本？我们用的是 5.4.1，应该5.0以后都可以，太老的cordorva可能会有这个问题。

**Comment by pipitang** [comment]
还有问题么？

**Comment by match08** [comment]
找出问题了  是你们ios使用json android使用&字符串。最后看源码才发现。写插件没统一数据格式。

**Comment by pipitang** [comment]
? 都是使用的json。。。

**Comment by pipitang** [comment]
而且插件init和json还是啥的也没啥关系哦，anyway, 解决了就好。

**Comment by match08** [comment]
我修改了插件 和android统一了下 都使用字符串，用&拼接好传入

**Comment by match08** [comment]
现在可以使用了，谢谢你的回复
