### ISSUE TITLE
ios 支付成功后没有回调

### ISSUE THREAD

**Issue by youyfeng** [pipitang/cordova-alipay-base#7]
ios 支付成功后，但是没有回调参数给我。
我后台传过来的是字符串（&）

Your system information:
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.2.4-nightly-1917
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.7.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by chenhg5** [comment]
同样没有回调，请问解决了吗

**Comment by pipitang** [comment]
抱歉，最近忙其他的东西，刚看见。主要是我们的项目里面一直用，没有问题，也没注意。

应该是后台传过来数据不兼容的问题，请参照 https://github.com/pipitang/cordova-alipay-base

**Comment by chenhg5** [comment]
之前解决了，好像是在 AppDelegate.m 文件加上下面这段：

```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    [[AlipaySDK defaultService] processOrderWithPaymentResult:url standbyCallback:^(NSDictionary *resultDic) {
          NSLog(@"@@@ %@", resultDic);
    }];
}
```
