### ISSUE TITLE
plugin_not_installed

### ISSUE THREAD

**Issue by JohnNiuNiu** [pipitang/cordova-alipay-base#9]
pay catch中提示plugin_not_installed，不知道为嘛？

只是先测试插件，代码如下：
  constructor(public navCtrl: NavController, private alipay: Alipay) {
    let alipayOrder:AlipayOrder;
    this.alipay.pay(alipayOrder)
      .then(result => {
        console.log(result); // Success
        alert('pay: ' + result);
      })
      .catch(error => {
        console.log(error); // Failed
        alert('pay error: ' + error);

      });
  }

**Comment by peng92055** [comment]
在安卓里测试也出现同样的bug

file:///android_asset/www/build/vendor.js: Line 80613 : Native: tried calling Alipay.pay, but the Alipay plugin is not installed.
I/chromium: [INFO:CONSOLE(80613)] "Native: tried calling Alipay.pay, but the Alipay plugin is not installed.", source: file:///android_asset/www/build/vendor.js (80613)
D/SystemWebChromeClient: file:///android_asset/www/build/vendor.js: Line 80619 : Install the Alipay plugin: 'ionic cordova plugin add cordova-alipay-base'
I/chromium: [INFO:CONSOLE(80619)] "Install the Alipay plugin: 'ionic cordova plugin add cordova-alipay-base'", source: file:///android_asset/www/build/vendor.js (80619)
D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 3772 : plugin_not_installed
I/chromium: [INFO:CONSOLE(3772)] "plugin_not_installed", source: file:///android_asset/www/build/main.js (3772)

求解

**Comment by JohnNiuNiu** [comment]
后面发现框架组件不对应Cordova插件会发生该错误；
使用https://github.com/xueron/cordova-alipay-base
it is work!
